# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /src/app
RUN mkdir -p /src/app/nodejs
COPY ./package.json ./package-lock.json /src/app/
# Install dependencies
RUN npm install
ENV NODE_ENV=docker
# Copy the rest of the Node.js application (inside the nodejs folder)
COPY nodejs/ ./nodejs/
# Expose the port the Node.js server will use
EXPOSE 5000

# Default to a shell for manual interaction
CMD ["sh"]
