version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: dockerfile.nodejs
    ports:
      - "5000:5000"
    volumes:
      - ./nodejs:/usr/src/app/nodejs
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=docker  # Indicate this is the Docker environment
      - hostClient=host.docker.internal  # Set the Docker-specific host
      - portClient=12345
      - CONNECTION_STRING=mongodb://host.docker.internal:27017/  # MongoDB connection for Docker
      - PORT=5000

  cpp:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "12345:12345"
    stdin_open: true
    tty: true

  frontend:
    extends:
      file: ./my-frontend/docker-compose.yml
      service: react-app  # Make sure this matches the service name in the frontend compose file
  android-builder:
    extends:
      file: ./src/client/android/docker-compose.yml
      service: android-builder  # Make sure the service name matches the one in the Android compose file


networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
