version: '3.8'

services:
  android-builder:
    build: .
    container_name: android-builder-container
    volumes:
      - .:/app
      - C:/Users/User/Desktop:/output
    working_dir: /app
    command: bash -c "./gradlew assembleDebug && cp /app/app/build/outputs/apk/debug/app-debug.apk /output/app-debug.apk"
